// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OOP_6.DAL.Context;

#nullable disable

namespace OOP_6.DAL.Migrations
{
    [DbContext(typeof(UserAppContext))]
    [Migration("20231025120115_InitMigration")]
    partial class InitMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OOP_6.DAL.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Address = "47650 Santiago Village, North Orphastad, Mali",
                            BirthDate = new DateTime(1984, 3, 27, 21, 4, 3, 225, DateTimeKind.Utc).AddTicks(7931),
                            Email = "Ubaldo_Hayes52@gmail.com",
                            FirstName = "Grayson",
                            LastName = "Tremblay",
                            RegisteredAt = new DateTime(2009, 6, 20, 12, 6, 24, 825, DateTimeKind.Utc).AddTicks(2649)
                        },
                        new
                        {
                            Id = 2L,
                            Address = "6685 Creola Inlet, Port Jorgeport, Chad",
                            BirthDate = new DateTime(2002, 10, 25, 7, 34, 46, 837, DateTimeKind.Utc).AddTicks(4),
                            Email = "Glenda.Tremblay51@gmail.com",
                            FirstName = "Cristian",
                            LastName = "Torp",
                            RegisteredAt = new DateTime(2017, 6, 20, 13, 54, 18, 915, DateTimeKind.Utc).AddTicks(3540)
                        },
                        new
                        {
                            Id = 3L,
                            Address = "51759 Braeden Centers, North Travon, Liechtenstein",
                            BirthDate = new DateTime(1994, 1, 17, 3, 16, 25, 742, DateTimeKind.Utc).AddTicks(1542),
                            Email = "Ian80@hotmail.com",
                            FirstName = "Emily",
                            LastName = "Ryan",
                            RegisteredAt = new DateTime(2001, 1, 6, 14, 28, 22, 182, DateTimeKind.Utc).AddTicks(7525)
                        },
                        new
                        {
                            Id = 4L,
                            Address = "18066 Kristopher Circles, Sigmundtown, Armenia",
                            BirthDate = new DateTime(1995, 12, 2, 23, 50, 59, 853, DateTimeKind.Utc).AddTicks(6235),
                            Email = "Danyka_Kilback@gmail.com",
                            FirstName = "Gustave",
                            LastName = "Klocko",
                            RegisteredAt = new DateTime(2011, 7, 15, 15, 40, 53, 782, DateTimeKind.Utc).AddTicks(421)
                        },
                        new
                        {
                            Id = 5L,
                            Address = "96037 Lindgren Manor, Chadton, Vietnam",
                            BirthDate = new DateTime(2007, 1, 29, 8, 3, 23, 110, DateTimeKind.Utc).AddTicks(9751),
                            Email = "Florencio14@yahoo.com",
                            FirstName = "Emilie",
                            LastName = "Kassulke",
                            RegisteredAt = new DateTime(2007, 12, 9, 22, 12, 33, 766, DateTimeKind.Utc).AddTicks(630)
                        },
                        new
                        {
                            Id = 6L,
                            Address = "80209 Trantow Vista, Flatleybury, Denmark",
                            BirthDate = new DateTime(1996, 12, 7, 19, 14, 37, 530, DateTimeKind.Utc).AddTicks(2017),
                            Email = "Millie61@hotmail.com",
                            FirstName = "Lola",
                            LastName = "Pollich",
                            RegisteredAt = new DateTime(2007, 6, 17, 1, 23, 57, 627, DateTimeKind.Utc).AddTicks(810)
                        },
                        new
                        {
                            Id = 7L,
                            Address = "6747 Gabrielle Springs, Kraigbury, Guam",
                            BirthDate = new DateTime(1997, 11, 18, 9, 13, 5, 405, DateTimeKind.Utc).AddTicks(3310),
                            Email = "Frank_Cruickshank@yahoo.com",
                            FirstName = "Archibald",
                            LastName = "Barrows",
                            RegisteredAt = new DateTime(2000, 3, 8, 11, 41, 25, 31, DateTimeKind.Utc).AddTicks(4891)
                        },
                        new
                        {
                            Id = 8L,
                            Address = "7678 Bechtelar Greens, North Enid, India",
                            BirthDate = new DateTime(1989, 3, 7, 12, 37, 59, 768, DateTimeKind.Utc).AddTicks(217),
                            Email = "Jacquelyn18@gmail.com",
                            FirstName = "Louvenia",
                            LastName = "Frami",
                            RegisteredAt = new DateTime(2009, 7, 12, 23, 16, 2, 521, DateTimeKind.Utc).AddTicks(6908)
                        },
                        new
                        {
                            Id = 9L,
                            Address = "330 Orville Way, Salmafurt, Faroe Islands",
                            BirthDate = new DateTime(2004, 11, 28, 7, 54, 13, 163, DateTimeKind.Utc).AddTicks(8069),
                            Email = "Duane59@yahoo.com",
                            FirstName = "Hope",
                            LastName = "Gottlieb",
                            RegisteredAt = new DateTime(2020, 5, 23, 2, 59, 19, 55, DateTimeKind.Utc).AddTicks(1288)
                        },
                        new
                        {
                            Id = 10L,
                            Address = "80826 Pansy Canyon, North Nealshire, Somalia",
                            BirthDate = new DateTime(1995, 3, 24, 2, 33, 49, 124, DateTimeKind.Utc).AddTicks(9199),
                            Email = "Ursula_Roberts13@yahoo.com",
                            FirstName = "Kattie",
                            LastName = "Raynor",
                            RegisteredAt = new DateTime(2017, 12, 30, 6, 20, 25, 900, DateTimeKind.Utc).AddTicks(2203)
                        },
                        new
                        {
                            Id = 11L,
                            Address = "381 Macejkovic Ford, Pagacport, Cook Islands",
                            BirthDate = new DateTime(1996, 9, 7, 6, 3, 7, 75, DateTimeKind.Utc).AddTicks(9216),
                            Email = "Nash.Crona@hotmail.com",
                            FirstName = "Eliza",
                            LastName = "Kassulke",
                            RegisteredAt = new DateTime(2002, 1, 29, 1, 34, 12, 652, DateTimeKind.Utc).AddTicks(2248)
                        },
                        new
                        {
                            Id = 12L,
                            Address = "14593 Treutel Summit, West Arnoborough, Falkland Islands (Malvinas)",
                            BirthDate = new DateTime(2006, 10, 16, 0, 34, 0, 566, DateTimeKind.Utc).AddTicks(8044),
                            Email = "Roy20@gmail.com",
                            FirstName = "Evangeline",
                            LastName = "Littel",
                            RegisteredAt = new DateTime(2014, 11, 11, 20, 52, 57, 564, DateTimeKind.Utc).AddTicks(331)
                        },
                        new
                        {
                            Id = 13L,
                            Address = "785 Willms Trail, Terrychester, Papua New Guinea",
                            BirthDate = new DateTime(1989, 2, 21, 14, 37, 45, 949, DateTimeKind.Utc).AddTicks(428),
                            Email = "Twila49@hotmail.com",
                            FirstName = "Lina",
                            LastName = "Wintheiser",
                            RegisteredAt = new DateTime(2011, 12, 29, 11, 11, 31, 559, DateTimeKind.Utc).AddTicks(5351)
                        },
                        new
                        {
                            Id = 14L,
                            Address = "5261 Beer Plain, West Adalberto, Belize",
                            BirthDate = new DateTime(1988, 8, 22, 23, 50, 49, 898, DateTimeKind.Utc).AddTicks(6987),
                            Email = "Katelin27@yahoo.com",
                            FirstName = "George",
                            LastName = "Daugherty",
                            RegisteredAt = new DateTime(2020, 5, 1, 13, 5, 43, 402, DateTimeKind.Utc).AddTicks(8667)
                        },
                        new
                        {
                            Id = 15L,
                            Address = "2743 Murray Stravenue, Orvalberg, Serbia",
                            BirthDate = new DateTime(1993, 8, 10, 23, 52, 35, 688, DateTimeKind.Utc).AddTicks(6298),
                            Email = "Courtney_Kunze@hotmail.com",
                            FirstName = "Kathlyn",
                            LastName = "Kris",
                            RegisteredAt = new DateTime(2016, 2, 29, 21, 45, 16, 621, DateTimeKind.Utc).AddTicks(5990)
                        },
                        new
                        {
                            Id = 16L,
                            Address = "688 Gayle Manor, Pearliefurt, Austria",
                            BirthDate = new DateTime(1989, 10, 20, 13, 29, 55, 506, DateTimeKind.Utc).AddTicks(6252),
                            Email = "Maia_Wyman@gmail.com",
                            FirstName = "Stephon",
                            LastName = "Goldner",
                            RegisteredAt = new DateTime(1996, 9, 29, 13, 6, 34, 90, DateTimeKind.Utc).AddTicks(4310)
                        },
                        new
                        {
                            Id = 17L,
                            Address = "549 Imelda Squares, Nicolasborough, Lithuania",
                            BirthDate = new DateTime(1990, 9, 14, 7, 11, 57, 212, DateTimeKind.Utc).AddTicks(4030),
                            Email = "Xavier_Schumm90@hotmail.com",
                            FirstName = "Jamey",
                            LastName = "Wuckert",
                            RegisteredAt = new DateTime(2020, 9, 24, 0, 3, 30, 623, DateTimeKind.Utc).AddTicks(6480)
                        },
                        new
                        {
                            Id = 18L,
                            Address = "4256 Collins Neck, New Oswaldbury, Kenya",
                            BirthDate = new DateTime(1990, 5, 21, 2, 5, 26, 523, DateTimeKind.Utc).AddTicks(900),
                            Email = "Carmine_McLaughlin@hotmail.com",
                            FirstName = "Haylee",
                            LastName = "Kessler",
                            RegisteredAt = new DateTime(2019, 12, 11, 17, 25, 47, 719, DateTimeKind.Utc).AddTicks(8082)
                        },
                        new
                        {
                            Id = 19L,
                            Address = "261 Maggio Gateway, Port Dax, French Polynesia",
                            BirthDate = new DateTime(2001, 11, 29, 17, 50, 42, 438, DateTimeKind.Utc).AddTicks(8619),
                            Email = "Howell.Nader71@gmail.com",
                            FirstName = "Alf",
                            LastName = "Shanahan",
                            RegisteredAt = new DateTime(2008, 8, 12, 5, 45, 44, 887, DateTimeKind.Utc).AddTicks(2532)
                        },
                        new
                        {
                            Id = 20L,
                            Address = "732 Antonina Oval, East Alessiamouth, Angola",
                            BirthDate = new DateTime(1989, 10, 2, 22, 54, 49, 57, DateTimeKind.Utc).AddTicks(3812),
                            Email = "Iliana_Crooks@gmail.com",
                            FirstName = "Dessie",
                            LastName = "Connelly",
                            RegisteredAt = new DateTime(2013, 5, 24, 9, 47, 52, 691, DateTimeKind.Utc).AddTicks(794)
                        },
                        new
                        {
                            Id = 21L,
                            Address = "51317 Breana Route, Anyaton, Tanzania",
                            BirthDate = new DateTime(1983, 8, 19, 3, 19, 53, 850, DateTimeKind.Utc).AddTicks(2591),
                            Email = "Issac.Lang@gmail.com",
                            FirstName = "Shana",
                            LastName = "Rempel",
                            RegisteredAt = new DateTime(2003, 4, 25, 0, 38, 21, 50, DateTimeKind.Utc).AddTicks(8376)
                        },
                        new
                        {
                            Id = 22L,
                            Address = "279 Gislason Knoll, East Khalilberg, Anguilla",
                            BirthDate = new DateTime(1992, 7, 10, 17, 1, 3, 396, DateTimeKind.Utc).AddTicks(3587),
                            Email = "Roosevelt.Fay75@gmail.com",
                            FirstName = "Moshe",
                            LastName = "Kunde",
                            RegisteredAt = new DateTime(1992, 7, 29, 17, 14, 7, 157, DateTimeKind.Utc).AddTicks(3108)
                        },
                        new
                        {
                            Id = 23L,
                            Address = "917 Ferry Mission, New Abnerburgh, Hungary",
                            BirthDate = new DateTime(2001, 7, 9, 20, 56, 10, 614, DateTimeKind.Utc).AddTicks(1942),
                            Email = "Ashtyn94@hotmail.com",
                            FirstName = "Norwood",
                            LastName = "Buckridge",
                            RegisteredAt = new DateTime(2001, 9, 3, 11, 43, 56, 769, DateTimeKind.Utc).AddTicks(2181)
                        },
                        new
                        {
                            Id = 24L,
                            Address = "574 Elva Meadows, Wilburnmouth, Saudi Arabia",
                            BirthDate = new DateTime(2001, 8, 18, 21, 57, 42, 216, DateTimeKind.Utc).AddTicks(8239),
                            Email = "Arvid80@hotmail.com",
                            FirstName = "Summer",
                            LastName = "Turner",
                            RegisteredAt = new DateTime(2018, 2, 2, 13, 23, 41, 703, DateTimeKind.Utc).AddTicks(3005)
                        },
                        new
                        {
                            Id = 25L,
                            Address = "72801 Bailey Forks, Port Horacio, Lithuania",
                            BirthDate = new DateTime(2006, 2, 27, 0, 17, 16, 509, DateTimeKind.Utc).AddTicks(4861),
                            Email = "Nico6@hotmail.com",
                            FirstName = "Jed",
                            LastName = "Cruickshank",
                            RegisteredAt = new DateTime(2019, 10, 7, 2, 10, 40, 255, DateTimeKind.Utc).AddTicks(6285)
                        },
                        new
                        {
                            Id = 26L,
                            Address = "7238 Gibson Lakes, Nasirview, New Zealand",
                            BirthDate = new DateTime(2001, 1, 21, 3, 10, 0, 73, DateTimeKind.Utc).AddTicks(4352),
                            Email = "Adolph2@yahoo.com",
                            FirstName = "Clint",
                            LastName = "Kohler",
                            RegisteredAt = new DateTime(2007, 7, 14, 11, 52, 52, 842, DateTimeKind.Utc).AddTicks(829)
                        },
                        new
                        {
                            Id = 27L,
                            Address = "21328 Hudson Mews, East Harmonyberg, Liberia",
                            BirthDate = new DateTime(2002, 12, 14, 8, 47, 53, 80, DateTimeKind.Utc).AddTicks(4814),
                            Email = "Kamren.Lebsack85@yahoo.com",
                            FirstName = "Darrell",
                            LastName = "Schmitt",
                            RegisteredAt = new DateTime(2006, 2, 15, 19, 33, 49, 581, DateTimeKind.Utc).AddTicks(7585)
                        },
                        new
                        {
                            Id = 28L,
                            Address = "251 Rene Mews, Lake Marjorytown, Sri Lanka",
                            BirthDate = new DateTime(1990, 7, 8, 23, 28, 17, 762, DateTimeKind.Utc).AddTicks(3588),
                            Email = "Daren27@yahoo.com",
                            FirstName = "Queenie",
                            LastName = "Schumm",
                            RegisteredAt = new DateTime(2017, 1, 25, 18, 59, 17, 409, DateTimeKind.Utc).AddTicks(6774)
                        },
                        new
                        {
                            Id = 29L,
                            Address = "707 Mireya Junctions, Lillieland, French Southern Territories",
                            BirthDate = new DateTime(1990, 4, 15, 7, 14, 6, 538, DateTimeKind.Utc).AddTicks(2757),
                            Email = "Jana_Moen@yahoo.com",
                            FirstName = "Aliya",
                            LastName = "O'Kon",
                            RegisteredAt = new DateTime(2009, 10, 31, 22, 15, 42, 454, DateTimeKind.Utc).AddTicks(2417)
                        },
                        new
                        {
                            Id = 30L,
                            Address = "0798 Vergie Squares, South Romaineport, Argentina",
                            BirthDate = new DateTime(1987, 12, 22, 14, 24, 3, 575, DateTimeKind.Utc).AddTicks(279),
                            Email = "Alessandra98@hotmail.com",
                            FirstName = "Angelina",
                            LastName = "Harris",
                            RegisteredAt = new DateTime(2006, 6, 30, 8, 28, 10, 193, DateTimeKind.Utc).AddTicks(212)
                        },
                        new
                        {
                            Id = 31L,
                            Address = "3543 Cristopher Wall, South Cyrus, Hong Kong",
                            BirthDate = new DateTime(2004, 1, 26, 21, 43, 36, 43, DateTimeKind.Utc).AddTicks(1392),
                            Email = "Christian6@hotmail.com",
                            FirstName = "Ona",
                            LastName = "Stokes",
                            RegisteredAt = new DateTime(2019, 2, 20, 12, 0, 28, 615, DateTimeKind.Utc).AddTicks(1173)
                        },
                        new
                        {
                            Id = 32L,
                            Address = "014 Schmitt Station, Kunzeport, Macao",
                            BirthDate = new DateTime(1997, 6, 20, 15, 8, 45, 394, DateTimeKind.Utc).AddTicks(2789),
                            Email = "Oliver_Schamberger@gmail.com",
                            FirstName = "Krystina",
                            LastName = "Ratke",
                            RegisteredAt = new DateTime(2008, 8, 1, 2, 15, 46, 121, DateTimeKind.Utc).AddTicks(6659)
                        },
                        new
                        {
                            Id = 33L,
                            Address = "219 Paucek Avenue, Fanniefurt, Congo",
                            BirthDate = new DateTime(1982, 8, 5, 20, 44, 44, 130, DateTimeKind.Utc).AddTicks(5708),
                            Email = "Lisette.Flatley41@hotmail.com",
                            FirstName = "Percival",
                            LastName = "Schamberger",
                            RegisteredAt = new DateTime(1990, 1, 29, 15, 41, 25, 462, DateTimeKind.Utc).AddTicks(8499)
                        },
                        new
                        {
                            Id = 34L,
                            Address = "941 Everett Square, Lexusmouth, Australia",
                            BirthDate = new DateTime(2004, 11, 16, 10, 17, 24, 677, DateTimeKind.Utc).AddTicks(7412),
                            Email = "Keara_Glover5@yahoo.com",
                            FirstName = "Marcellus",
                            LastName = "Dare",
                            RegisteredAt = new DateTime(2018, 7, 12, 21, 38, 16, 628, DateTimeKind.Utc).AddTicks(9192)
                        },
                        new
                        {
                            Id = 35L,
                            Address = "6165 Lera Cove, Lake Sydni, Brazil",
                            BirthDate = new DateTime(2008, 7, 21, 12, 46, 59, 1, DateTimeKind.Utc).AddTicks(7095),
                            Email = "Solon_Hartmann16@gmail.com",
                            FirstName = "Travis",
                            LastName = "Champlin",
                            RegisteredAt = new DateTime(2015, 5, 11, 15, 31, 6, 13, DateTimeKind.Utc).AddTicks(4146)
                        },
                        new
                        {
                            Id = 36L,
                            Address = "53572 Fisher Junction, Ahmedfort, Western Sahara",
                            BirthDate = new DateTime(1985, 9, 3, 5, 6, 31, 446, DateTimeKind.Utc).AddTicks(7420),
                            Email = "Johathan.Mante67@gmail.com",
                            FirstName = "Malika",
                            LastName = "Kuhic",
                            RegisteredAt = new DateTime(2016, 4, 4, 14, 24, 34, 113, DateTimeKind.Utc).AddTicks(3174)
                        },
                        new
                        {
                            Id = 37L,
                            Address = "132 Hessel Lake, Lake Molly, Greenland",
                            BirthDate = new DateTime(1988, 12, 9, 10, 36, 38, 699, DateTimeKind.Utc).AddTicks(1628),
                            Email = "Benedict95@hotmail.com",
                            FirstName = "Rashad",
                            LastName = "Bartoletti",
                            RegisteredAt = new DateTime(1995, 1, 5, 18, 53, 49, 894, DateTimeKind.Utc).AddTicks(2267)
                        },
                        new
                        {
                            Id = 38L,
                            Address = "365 Pagac Groves, Weimannbury, Sao Tome and Principe",
                            BirthDate = new DateTime(1990, 12, 11, 10, 58, 9, 981, DateTimeKind.Utc).AddTicks(4775),
                            Email = "Bridgette63@gmail.com",
                            FirstName = "Geovanni",
                            LastName = "Rempel",
                            RegisteredAt = new DateTime(2002, 2, 11, 19, 14, 0, 647, DateTimeKind.Utc).AddTicks(7140)
                        },
                        new
                        {
                            Id = 39L,
                            Address = "64379 Luther Trail, Camillaborough, American Samoa",
                            BirthDate = new DateTime(2007, 9, 30, 13, 20, 11, 561, DateTimeKind.Utc).AddTicks(8542),
                            Email = "Virgie.Jenkins@gmail.com",
                            FirstName = "Elinor",
                            LastName = "Purdy",
                            RegisteredAt = new DateTime(2008, 10, 31, 9, 5, 20, 486, DateTimeKind.Utc).AddTicks(3388)
                        },
                        new
                        {
                            Id = 40L,
                            Address = "0912 Skiles Cliffs, Kirstinview, Saint Vincent and the Grenadines",
                            BirthDate = new DateTime(1994, 9, 29, 16, 37, 59, 548, DateTimeKind.Utc).AddTicks(5432),
                            Email = "Marco_Parisian@hotmail.com",
                            FirstName = "Marjolaine",
                            LastName = "Brakus",
                            RegisteredAt = new DateTime(1995, 8, 16, 6, 16, 38, 836, DateTimeKind.Utc).AddTicks(1737)
                        },
                        new
                        {
                            Id = 41L,
                            Address = "86637 Lowell Meadows, Lake Ashley, Uruguay",
                            BirthDate = new DateTime(2002, 12, 30, 16, 32, 11, 905, DateTimeKind.Utc).AddTicks(5685),
                            Email = "Daren_Fadel62@gmail.com",
                            FirstName = "Herman",
                            LastName = "Rosenbaum",
                            RegisteredAt = new DateTime(2010, 3, 24, 12, 5, 24, 468, DateTimeKind.Utc).AddTicks(5169)
                        },
                        new
                        {
                            Id = 42L,
                            Address = "4294 Zulauf Knolls, Tillmanport, Saint Helena",
                            BirthDate = new DateTime(1991, 6, 23, 5, 21, 16, 800, DateTimeKind.Utc).AddTicks(4998),
                            Email = "Dion_Kautzer19@hotmail.com",
                            FirstName = "Easter",
                            LastName = "Rippin",
                            RegisteredAt = new DateTime(2007, 3, 18, 4, 23, 5, 218, DateTimeKind.Utc).AddTicks(3)
                        },
                        new
                        {
                            Id = 43L,
                            Address = "4152 Volkman Village, Lake Brittany, Bangladesh",
                            BirthDate = new DateTime(2004, 2, 28, 16, 30, 32, 828, DateTimeKind.Utc).AddTicks(6567),
                            Email = "Colby_Prohaska@gmail.com",
                            FirstName = "Eloisa",
                            LastName = "Nikolaus",
                            RegisteredAt = new DateTime(2007, 10, 25, 15, 50, 6, 437, DateTimeKind.Utc).AddTicks(7876)
                        },
                        new
                        {
                            Id = 44L,
                            Address = "46358 Treutel Forge, Steuberchester, Costa Rica",
                            BirthDate = new DateTime(1981, 9, 27, 13, 18, 8, 688, DateTimeKind.Utc).AddTicks(889),
                            Email = "Jordan15@hotmail.com",
                            FirstName = "Mae",
                            LastName = "Grady",
                            RegisteredAt = new DateTime(2002, 6, 4, 7, 49, 49, 392, DateTimeKind.Utc).AddTicks(5914)
                        },
                        new
                        {
                            Id = 45L,
                            Address = "72194 Carter Wall, Jacobifurt, Gambia",
                            BirthDate = new DateTime(1982, 2, 10, 17, 34, 22, 699, DateTimeKind.Utc).AddTicks(6573),
                            Email = "Steve_Reinger@hotmail.com",
                            FirstName = "Jimmie",
                            LastName = "Reinger",
                            RegisteredAt = new DateTime(1992, 1, 10, 12, 57, 12, 350, DateTimeKind.Utc).AddTicks(8910)
                        },
                        new
                        {
                            Id = 46L,
                            Address = "774 Schamberger Landing, South Jordy, Yemen",
                            BirthDate = new DateTime(1997, 2, 11, 9, 33, 25, 369, DateTimeKind.Utc).AddTicks(3038),
                            Email = "Noemie.Stark@hotmail.com",
                            FirstName = "Mario",
                            LastName = "Wiegand",
                            RegisteredAt = new DateTime(2013, 1, 1, 1, 49, 29, 604, DateTimeKind.Utc).AddTicks(9628)
                        },
                        new
                        {
                            Id = 47L,
                            Address = "0998 Izaiah Meadow, Feestton, Macedonia",
                            BirthDate = new DateTime(1984, 8, 27, 17, 39, 31, 268, DateTimeKind.Utc).AddTicks(9353),
                            Email = "Domenico.Prohaska92@yahoo.com",
                            FirstName = "Furman",
                            LastName = "Oberbrunner",
                            RegisteredAt = new DateTime(1998, 9, 15, 3, 59, 49, 821, DateTimeKind.Utc).AddTicks(7979)
                        },
                        new
                        {
                            Id = 48L,
                            Address = "31416 Lucinda Groves, Douglasville, Equatorial Guinea",
                            BirthDate = new DateTime(1997, 11, 9, 13, 4, 5, 169, DateTimeKind.Utc).AddTicks(9923),
                            Email = "Eleazar_Zulauf@yahoo.com",
                            FirstName = "Vilma",
                            LastName = "Stanton",
                            RegisteredAt = new DateTime(2022, 12, 31, 4, 13, 43, 491, DateTimeKind.Utc).AddTicks(5391)
                        },
                        new
                        {
                            Id = 49L,
                            Address = "43445 Edmond Ramp, Douglashaven, Yemen",
                            BirthDate = new DateTime(2004, 6, 6, 1, 10, 27, 878, DateTimeKind.Utc).AddTicks(8199),
                            Email = "Jovany_Pacocha@yahoo.com",
                            FirstName = "Elise",
                            LastName = "O'Kon",
                            RegisteredAt = new DateTime(2018, 8, 26, 12, 27, 10, 927, DateTimeKind.Utc).AddTicks(6109)
                        },
                        new
                        {
                            Id = 50L,
                            Address = "65825 Selina Corner, Wernermouth, Belarus",
                            BirthDate = new DateTime(1981, 3, 18, 0, 6, 43, 331, DateTimeKind.Utc).AddTicks(7896),
                            Email = "Okey32@gmail.com",
                            FirstName = "Lyric",
                            LastName = "Reynolds",
                            RegisteredAt = new DateTime(2002, 7, 24, 8, 15, 1, 848, DateTimeKind.Utc).AddTicks(97)
                        },
                        new
                        {
                            Id = 51L,
                            Address = "738 Tevin Squares, East Nelsonberg, Cocos (Keeling) Islands",
                            BirthDate = new DateTime(1989, 10, 26, 22, 38, 35, 253, DateTimeKind.Utc).AddTicks(1273),
                            Email = "Elyssa5@gmail.com",
                            FirstName = "Antonia",
                            LastName = "Stanton",
                            RegisteredAt = new DateTime(2008, 4, 6, 5, 43, 27, 609, DateTimeKind.Utc).AddTicks(6142)
                        },
                        new
                        {
                            Id = 52L,
                            Address = "29406 Murray Flats, Alizastad, Togo",
                            BirthDate = new DateTime(1998, 9, 27, 19, 25, 10, 394, DateTimeKind.Utc).AddTicks(8844),
                            Email = "Nat.Osinski@hotmail.com",
                            FirstName = "Conor",
                            LastName = "Shields",
                            RegisteredAt = new DateTime(2016, 9, 9, 10, 0, 18, 768, DateTimeKind.Utc).AddTicks(1197)
                        },
                        new
                        {
                            Id = 53L,
                            Address = "48544 Nolan Harbors, Dareburgh, Chad",
                            BirthDate = new DateTime(1996, 5, 7, 8, 44, 29, 544, DateTimeKind.Utc).AddTicks(1080),
                            Email = "Myrtis_Keebler81@hotmail.com",
                            FirstName = "Naomi",
                            LastName = "Bauch",
                            RegisteredAt = new DateTime(1998, 11, 28, 13, 18, 32, 962, DateTimeKind.Utc).AddTicks(7743)
                        },
                        new
                        {
                            Id = 54L,
                            Address = "7881 Cassandre River, Lake Prince, Austria",
                            BirthDate = new DateTime(2001, 1, 26, 8, 53, 23, 780, DateTimeKind.Utc).AddTicks(760),
                            Email = "Amparo73@gmail.com",
                            FirstName = "Stevie",
                            LastName = "Ortiz",
                            RegisteredAt = new DateTime(2007, 5, 14, 5, 5, 37, 865, DateTimeKind.Utc).AddTicks(8505)
                        },
                        new
                        {
                            Id = 55L,
                            Address = "8767 Kub Square, New Isaac, Tajikistan",
                            BirthDate = new DateTime(1983, 1, 16, 0, 59, 23, 499, DateTimeKind.Utc).AddTicks(2005),
                            Email = "Beatrice92@hotmail.com",
                            FirstName = "Camille",
                            LastName = "Moore",
                            RegisteredAt = new DateTime(1991, 7, 23, 8, 36, 21, 409, DateTimeKind.Utc).AddTicks(509)
                        },
                        new
                        {
                            Id = 56L,
                            Address = "5245 Linwood Motorway, Monserrateton, Niue",
                            BirthDate = new DateTime(1997, 5, 30, 5, 21, 47, 897, DateTimeKind.Utc).AddTicks(5350),
                            Email = "Juanita_Monahan42@hotmail.com",
                            FirstName = "Dax",
                            LastName = "Deckow",
                            RegisteredAt = new DateTime(2003, 3, 7, 1, 14, 41, 366, DateTimeKind.Utc).AddTicks(5552)
                        },
                        new
                        {
                            Id = 57L,
                            Address = "620 Troy Islands, Burnicemouth, Anguilla",
                            BirthDate = new DateTime(1986, 5, 1, 8, 58, 2, 563, DateTimeKind.Utc).AddTicks(741),
                            Email = "Jonathan.Predovic@gmail.com",
                            FirstName = "Zita",
                            LastName = "Berge",
                            RegisteredAt = new DateTime(2022, 12, 5, 4, 30, 54, 605, DateTimeKind.Utc).AddTicks(9831)
                        },
                        new
                        {
                            Id = 58L,
                            Address = "845 Nolan Vista, North Rossie, Egypt",
                            BirthDate = new DateTime(2005, 10, 27, 11, 42, 8, 514, DateTimeKind.Utc).AddTicks(5017),
                            Email = "Carey.Leannon83@gmail.com",
                            FirstName = "Henderson",
                            LastName = "Ebert",
                            RegisteredAt = new DateTime(2015, 1, 29, 4, 53, 50, 488, DateTimeKind.Utc).AddTicks(5013)
                        },
                        new
                        {
                            Id = 59L,
                            Address = "5883 Hyatt Forest, Lake Vincemouth, Philippines",
                            BirthDate = new DateTime(1986, 6, 29, 8, 26, 43, 438, DateTimeKind.Utc).AddTicks(11),
                            Email = "Letitia.Cruickshank@gmail.com",
                            FirstName = "Hilma",
                            LastName = "Mayer",
                            RegisteredAt = new DateTime(2000, 11, 26, 23, 9, 44, 66, DateTimeKind.Utc).AddTicks(5135)
                        },
                        new
                        {
                            Id = 60L,
                            Address = "09677 Sauer Prairie, Lutherside, Ecuador",
                            BirthDate = new DateTime(2000, 12, 12, 23, 32, 35, 567, DateTimeKind.Utc).AddTicks(5991),
                            Email = "Lorenzo_Abshire17@yahoo.com",
                            FirstName = "Monserrate",
                            LastName = "O'Reilly",
                            RegisteredAt = new DateTime(2006, 5, 11, 6, 27, 27, 43, DateTimeKind.Utc).AddTicks(7262)
                        },
                        new
                        {
                            Id = 61L,
                            Address = "67076 Henriette Village, South Carmela, Oman",
                            BirthDate = new DateTime(1982, 9, 13, 6, 46, 12, 190, DateTimeKind.Utc).AddTicks(4063),
                            Email = "Ronaldo12@hotmail.com",
                            FirstName = "Leonel",
                            LastName = "Oberbrunner",
                            RegisteredAt = new DateTime(1990, 10, 28, 14, 52, 26, 144, DateTimeKind.Utc).AddTicks(3569)
                        },
                        new
                        {
                            Id = 62L,
                            Address = "3981 Frami Brooks, Verniceton, Martinique",
                            BirthDate = new DateTime(1993, 12, 26, 6, 6, 15, 294, DateTimeKind.Utc).AddTicks(1726),
                            Email = "Davion55@gmail.com",
                            FirstName = "Florencio",
                            LastName = "Goodwin",
                            RegisteredAt = new DateTime(2011, 2, 28, 5, 38, 31, 551, DateTimeKind.Utc).AddTicks(3169)
                        },
                        new
                        {
                            Id = 63L,
                            Address = "5590 Lindgren Lock, New Malvinachester, United States of America",
                            BirthDate = new DateTime(1980, 11, 21, 1, 51, 27, 652, DateTimeKind.Utc).AddTicks(3228),
                            Email = "Maci47@hotmail.com",
                            FirstName = "Velva",
                            LastName = "Will",
                            RegisteredAt = new DateTime(1999, 7, 31, 1, 45, 29, 454, DateTimeKind.Utc).AddTicks(4045)
                        },
                        new
                        {
                            Id = 64L,
                            Address = "332 Hamill Estate, Willowfurt, Heard Island and McDonald Islands",
                            BirthDate = new DateTime(1999, 8, 21, 1, 21, 3, 121, DateTimeKind.Utc).AddTicks(6831),
                            Email = "Milan.Hegmann57@hotmail.com",
                            FirstName = "Oliver",
                            LastName = "Renner",
                            RegisteredAt = new DateTime(2011, 4, 23, 6, 34, 14, 840, DateTimeKind.Utc).AddTicks(19)
                        },
                        new
                        {
                            Id = 65L,
                            Address = "9131 Lebsack Dale, West Zacharytown, Qatar",
                            BirthDate = new DateTime(2002, 3, 2, 4, 13, 28, 494, DateTimeKind.Utc).AddTicks(4215),
                            Email = "Casimer.Monahan89@gmail.com",
                            FirstName = "Talia",
                            LastName = "Kemmer",
                            RegisteredAt = new DateTime(2007, 7, 17, 0, 48, 19, 681, DateTimeKind.Utc).AddTicks(1493)
                        },
                        new
                        {
                            Id = 66L,
                            Address = "11316 Greenfelder Key, Corkerybury, Norfolk Island",
                            BirthDate = new DateTime(1985, 2, 4, 5, 20, 24, 344, DateTimeKind.Utc).AddTicks(2565),
                            Email = "Gust.Considine62@hotmail.com",
                            FirstName = "Noel",
                            LastName = "Ritchie",
                            RegisteredAt = new DateTime(2002, 10, 11, 5, 20, 5, 858, DateTimeKind.Utc).AddTicks(8150)
                        },
                        new
                        {
                            Id = 67L,
                            Address = "07933 Sarah Curve, Streichton, Svalbard & Jan Mayen Islands",
                            BirthDate = new DateTime(2006, 8, 18, 1, 56, 0, 412, DateTimeKind.Utc).AddTicks(8632),
                            Email = "Malika.Armstrong18@hotmail.com",
                            FirstName = "Breanne",
                            LastName = "Dooley",
                            RegisteredAt = new DateTime(2022, 11, 7, 18, 40, 1, 405, DateTimeKind.Utc).AddTicks(6150)
                        },
                        new
                        {
                            Id = 68L,
                            Address = "8560 Dorthy Village, Naderstad, Germany",
                            BirthDate = new DateTime(2002, 7, 3, 12, 49, 30, 55, DateTimeKind.Utc).AddTicks(7685),
                            Email = "Gretchen_Roberts@hotmail.com",
                            FirstName = "Rodrigo",
                            LastName = "Balistreri",
                            RegisteredAt = new DateTime(2009, 1, 4, 16, 9, 53, 827, DateTimeKind.Utc).AddTicks(2807)
                        },
                        new
                        {
                            Id = 69L,
                            Address = "8980 Dorothy Underpass, North Cleo, French Polynesia",
                            BirthDate = new DateTime(1988, 9, 29, 19, 21, 19, 526, DateTimeKind.Utc).AddTicks(9352),
                            Email = "Wilson89@hotmail.com",
                            FirstName = "Clare",
                            LastName = "Cronin",
                            RegisteredAt = new DateTime(2019, 11, 4, 14, 35, 1, 329, DateTimeKind.Utc).AddTicks(7682)
                        },
                        new
                        {
                            Id = 70L,
                            Address = "6578 Justus Street, DuBuqueburgh, Tonga",
                            BirthDate = new DateTime(2008, 8, 23, 6, 40, 37, 886, DateTimeKind.Utc).AddTicks(8885),
                            Email = "Olaf.Rath46@gmail.com",
                            FirstName = "Moriah",
                            LastName = "Schmeler",
                            RegisteredAt = new DateTime(2018, 10, 10, 10, 30, 52, 728, DateTimeKind.Utc).AddTicks(7867)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
